

create extension if not exists pgcrypto;

-- Profiles table for role-based admin checks.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'viewer' check (role in ('admin', 'viewer')),
  created_at timestamptz not null default now()
);

-- Teams managed by admin dashboard.
create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  team_name text not null,
  competition text not null,
  school text,
  created_at timestamptz not null default now()
);

-- Score entries managed by admin dashboard.
create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  team_id bigint not null references public.teams(id) on delete cascade,
  competition text not null,
  round_number integer not null check (round_number > 0),
  score numeric not null,
  notes text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

-- Shared key/value config used by admin + public pages.
create table if not exists public.app_config (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

-- Trigger to stamp updated_at automatically.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_app_config_updated_at on public.app_config;
create trigger set_app_config_updated_at
before update on public.app_config
for each row
execute function public.set_updated_at();

-- Enable RLS.
alter table public.profiles enable row level security;
alter table public.teams enable row level security;
alter table public.scores enable row level security;
alter table public.app_config enable row level security;

-- Helper function for admin checks.
create or replace function public.is_admin(uid uuid)
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from public.profiles
    where id = uid and role = 'admin'
  );
$$;

-- Profiles policies.
drop policy if exists "Profiles self read" on public.profiles;
create policy "Profiles self read"
on public.profiles
for select
to authenticated
using (id = auth.uid());

drop policy if exists "Profiles admin read" on public.profiles;
create policy "Profiles admin read"
on public.profiles
for select
to authenticated
using (public.is_admin(auth.uid()));

-- Teams policies.
drop policy if exists "Teams public read" on public.teams;
create policy "Teams public read"
on public.teams
for select
to anon, authenticated
using (true);

drop policy if exists "Teams admin write" on public.teams;
create policy "Teams admin write"
on public.teams
for all
to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

-- Scores policies.
drop policy if exists "Scores public read" on public.scores;
create policy "Scores public read"
on public.scores
for select
to anon, authenticated
using (true);

drop policy if exists "Scores admin write" on public.scores;
create policy "Scores admin write"
on public.scores
for all
to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

-- App config policies.
drop policy if exists "App config public read" on public.app_config;
create policy "App config public read"
on public.app_config
for select
to anon, authenticated
using (true);

drop policy if exists "App config admin write" on public.app_config;
create policy "App config admin write"
on public.app_config
for all
to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

-- Optional seed rows so public pages have first-load values.
insert into public.app_config (key, value)
values
  ('site_settings', '{}'::jsonb),
  ('competitions', '["Maze","Formula 1","Performance","SumoBots","Rescue Line","Rescue Maze","Soccer","OnStage"]'::jsonb),
  ('schedule_competitions', '["Maze","Formula 1","Performance","SumoBots","Rescue Line","Rescue Maze","Soccer","OnStage"]'::jsonb),
  ('schedule_events', '[]'::jsonb),
  ('league_details', '{}'::jsonb),
  ('bracket_state', '{}'::jsonb)
on conflict (key) do nothing;
